# Generated by Django 5.0.6 on 2024-06-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='MessageStatus',
        ),
    ]
